### ISSUE TITLE
[flutter] Error when building the app ('create' overrides nothing on FlutterStorylyView.kt)

### ISSUE THREAD

**Issue by lazarohcm** [Netvent/storyly-mobile#184]
Hi, I'm trying to set up Storyly on my app and I get this error when I try to run for Android with the specifications listed below. 
I couldn't find anything similar in the issues here, so I wonder if anyone else is facing this issue or has faced it before? Maybe I'm missing something in the setup?

## Environment Details
**Storyly SDK Version:** 1.2.0
**Flutter SDK Version:** 3.0.1
**Platform:**
- [x] Android 
**Additional Info:**
The app is configured with Kotlin `1.6.10`. `useAndroidX` and `enableJetifier` is set to true.

- [ ] iOS
**Device Model:** ---
**Device OS Version:** ---

Console error
```
e: /Users/user/DevEnv/flutter/.pub-cache/hosted/pub.dartlang.org/storyly_flutter-1.20.0/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/FlutterStorylyView.kt: (22, 1): Class 'FlutterStorylyViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /Users/user/DevEnv/flutter/.pub-cache/hosted/pub.dartlang.org/storyly_flutter-1.20.0/android/src/main/kotlin/com/appsamurai/storyly/storyly_flutter/FlutterStorylyView.kt: (25, 5): 'create' overrides nothing
```

## Expected Behavior
Just trying to start up the application

## Current Behavior
App fails to compile

## Steps to Reproduce
1. Configured the project for Android
2. `flutter run` on the project folder

**Comment by BrunoJurkovic** [comment]
I am experiencing this issue as well.

**Comment by utkudenis** [comment]
I think  ı have the similar problem 
e: C:\Users\utku\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\storyly_flutter-1.20.0\android\src\main\kotlin\com\appsamurai\storyly\storyly_flutter\FlutterStorylyView.kt: (22, 1): Class 'FlutterStorylyViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\Users\utku\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\storyly_flutter-1.20.0\android\src\main\kotlin\com\appsamurai\storyly\storyly_flutter\FlutterStorylyView.kt: (25, 5): 'create' overrides nothing

**Comment by masterwok** [comment]
I'm also experiencing this issue.

**Comment by levent-oral** [comment]
Hello,

We're working on Flutter 3.0 support for storyly_flutter package. 

Moreover, There is the [#185](https://github.com/Netvent/storyly-mobile/pull/185) PR to overcome this issue. Thanks to @lazarohcm :) You can apply these changes on your environment before storyly_flutter release.

We're checking the other possible changes in package and backward compatibility for the customers who do not update Flutter 3.0 yet.

Thanks!

**Comment by levent-oral** [comment]
We've released [storyly_flutter@1.23.0](https://github.com/Netvent/storyly-mobile/blob/master/flutter/storyly_flutter/CHANGELOG.md#1230-27062022) version to support Flutter 3.0.
